### ISSUE TITLE
No class methods 'enum' and 'enums' defined

### ISSUE THREAD

**Issue by rovf** [mezuka/enum#4]
According to the usage description on https://github.com/mezuka/enum, the following should work:

`
require 'enum'
class Side < Enum::Base
  values :left, :right
end
Side.enum(:left)
Side.enums(:left, :right) 
`

However, the methods `enum` and `enums` don't exist (NoMethodError: undefined method `enum' for Side:Class)

Gem version 0.2.0

**Comment by rovf** [comment]
I just noticed that the usage instructions on the website are incorrect, but the README.md seems to be correct. It should be

```
 Side.take(:left)
```

instead of 

```
Side.enum(:left)
```

**Comment by ka8725** [comment]
Hi, @rovf . Thanks for your response. The README that you see on the page is from `master` branch. For `0.2.0` there was another API: https://github.com/mezuka/enum/tree/9cebcc88bfeaa622f8cf79c395647cfcc4c7cb84

Sorry about that. I will create a new version once I have time. For now you can just pick gem from master branch.

**Comment by rovf** [comment]
Thanks for the information. I think I will stick with 0.2.0, because
this is what we get when we do a gem install with default values.

**Comment by ka8725** [comment]
New version released.
